# Generated by Django 4.2.2 on 2023-07-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('discount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Discount')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Sales Order Detail',
                'verbose_name_plural': 'Sales Order Details',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date of sale')),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Discount')),
                ('total', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Total')),
                ('paid_with', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Paid with $')),
                ('change', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Change $')),
                ('products', models.ManyToManyField(through='invoice.SalesOrderDetail', to='product.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Sales Order Header',
                'verbose_name_plural': 'Sales Order Headers',
            },
        ),
        migrations.AddField(
            model_name='salesorderdetail',
            name='id_sales_order_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.salesorderheader', verbose_name='Sales Order Header'),
        ),
    ]
