# Generated by Django 4.2.2 on 2023-07-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderdetail',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='salesorderdetail',
            old_name='id_sales_order_header',
            new_name='sales_order_header',
        ),
    ]
