# Generated by Django 4.2.2 on 2023-08-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_id_product_salesorderdetail_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderdetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderdetail',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
