# Generated by Django 4.2.2 on 2023-07-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales_order_header', '0002_alter_salesorderheader_options'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('discount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Discount')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
                ('id_sales_order_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_order_header.salesorderheader', verbose_name='Sales Order Header')),
            ],
            options={
                'verbose_name': 'Sales Order Detail',
                'verbose_name_plural': 'Sales Order Details',
            },
        ),
    ]
