# Generated by Django 4.2.2 on 2023-07-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderHeader',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date of sale')),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Discount')),
                ('total', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Total')),
                ('paid_with', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Paid with $')),
                ('change', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Change $')),
            ],
            options={
                'verbose_name': 'Base Model',
                'abstract': False,
            },
        ),
    ]
