# Generated by Django 4.2.2 on 2023-07-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_order_header', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorderheader',
            options={'verbose_name': 'Sales Order Header', 'verbose_name_plural': 'Sales Order Headers'},
        ),
    ]
